Issue: #8 - Add site as an option for bulk redirect import
LUKKIEN/wagtail-marketing-addons pull request #11
Opened 2019-10-15 09:05 UTC by BramManuel

I have made an option to select a site for the bulk upload. 

Things that still need work are:

- [ ] Styling of the form

2019-10-16 15:21 UTC, leewesleyv requested changes
Looking good! I've left some comments that should be addressed before merging this.

2019-10-16 15:21 UTC, leewesleyv commented on src/wagtail_marketing/forms.py
>          file = self.cleaned_data.get('file')
If we don't need to validate whether the file is present, it also means we can do a lookup instead of a get.

2019-10-16 15:21 UTC, leewesleyv commented on src/wagtail_marketing/templates/wagtailredirects/index.html
> +                </div>
We render the form here by manually typing out the fields. The ideal situation would be that we could pass the form as a context variable to the wagtailredirects index view. Since this is not that easily achievable, I would suggest getting the form through a template tag. This way it will at least be a bit more flexible than the current implementation.

2019-10-17 11:01 UTC, leewesleyv approved these changes

2019-11-27 12:23 UTC, jjanssen commented
Thanks! Merged with 84af6f5

2019-11-27 12:23 UTC, closed without merging